#!/bin/sh

#update apt
sudo apt update

#update the system
sudo apt upgrade

#get the programs I want
sudo apt-get install --yes krita python3 vlc git nodejs geany bluefish audacity inkscape gimp npm rpi-imager

#extra stuff not in repositories
wget https://code.visualstudio.com/sha/download?build=stable&os=linux-deb-x64
dpkg -install code_*.deb


